login:
    path: /login
    controller: App\Controller\SecurityController::login

pass_recovery:
    path: /passwordRecovery
    controller: App\Controller\SecurityController::recovery

app_logout:
    path: /logout

registration:
    path: /registration
    controller: App\Controller\RegistrationController::register

main:
    path: /
    controller: App\Controller\MainController::main

children_list:
    path: /children
    controller: App\Controller\ChildController::list

children_detail:
    path: /children/{id}
    controller: App\Controller\ChildController::detail
    requirements:
        id: '\d+'

news_list:
    path: /news
    controller: App\Controller\NewsController::list

news_cards:
    path: /news/cards
    controller: App\Controller\NewsController::cards

news_detail:
    path: /news/{id}
    controller: App\Controller\NewsController::detail
    requirements:
        id: '\d+'

partners:
    path: /partners
    controller: App\Controller\MainController::partners

docs:
    path: /docs
    controller: App\Controller\MainController::docs

reports:
    path: /reports
    controller: App\Controller\MainController::reports

contacts:
    path: /contacts
    controller: App\Controller\MainController::contacts

help:
    path: /help
    controller: App\Controller\MainController::help

donate:
    path: /donate
    controller: App\Controller\MainController::donate

account_main:
    path: /account
    controller: App\Controller\AccountController::main

account_myaccount:
    path: /account/myaccount
    controller: App\Controller\AccountController::myaccount

account_history:
    path: /account/history
    controller: App\Controller\AccountController::history

account_referrals:
    path: /account/referrals
    controller: App\Controller\AccountController::referrals

account_recurrent:
    path: /account/recurrent
    controller: App\Controller\AccountController::recurrent

panel_auth:
    path: /panel/auth
    controller: App\Controller\PanelController::auth

panel_main:
    path: /panel/main
    controller: App\Controller\PanelController::main

panel_users:
    path: /panel/users
    controller: App\Controller\PanelController::users

panel_requests:
    path: /panel/requests
    controller: App\Controller\PanelController::requests

panel_payments:
    path: /panel/payments
    controller: App\Controller\PanelController::payments

user_controller:
    path: /user
    controller: App\Controller\UserController::index
