login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

registration:
    path: /registration
    controller: App\Controller\RegistrationController::index

child_main:
    path: /
    controller: App\Controller\ChildController::main

child_kids:
    path: /kids
    controller: App\Controller\ChildController::kids

child_view:
    path: /kids/detail
    controller: App\Controller\ChildController::view

child_newscards:
    path: /news
    controller: App\Controller\ChildController::newscards

child_newsdetail:
    path: /news/newsdetail
    controller: App\Controller\ChildController::newsdetail

child_partners:
    path: /partners
    controller: App\Controller\ChildController::partners

child_docs:
    path: /docs
    controller: App\Controller\ChildController::docs

child_reports:
    path: /reports
    controller: App\Controller\ChildController::reports

child_contacts:
    path: /contacts
    controller: App\Controller\ChildController::contacts

child_help:
    path: /help
    controller: App\Controller\ChildController::help

child_onlinehelp:
    path: /onlinehelp
    controller: App\Controller\ChildController::onlinehelp

child_account:
    path: /account
    controller: App\Controller\AccountController::account

child_myaccount:
    path: /account/myaccount
    controller: App\Controller\AccountController::myaccount

child_history:
    path: /account/history
    controller: App\Controller\AccountController::history

child_referrals:
    path: /account/referrals
    controller: App\Controller\AccountController::referrals

child_recurrent:
    path: /account/recurrent
    controller: App\Controller\AccountController::recurrent

panel_auth:
    path: /panel/auth
    controller: App\Controller\PanelController::auth

panel_users:
    path: /panel/users
    controller: App\Controller\PanelController::users





user_controller:
    path: /user
    controller: App\Controller\UserController::index

child_login:
    path: /child/login
    controller: App\Controller\ChildController::login
