index:
    path: /
    controller: App\Controller\DefaultController::index

user_controller:
    path: /user
    controller: App\Controller\UserController::index

child_view:
    path: /child/view
    controller: App\Controller\ChildController::view

child_registration:
    path: /child/registration
    controller: App\Controller\ChildController::registration
